version: "3.9"
services:
    ######################################################
    ## Cassandra #########################################
    ######################################################
    cassandra:
      container_name: cassandra
      image: bitnami/cassandra:latest
      # ports:
      #   - '7000:7000'
      #   - '9042:9042'
      environment:
        - CASSANDRA_SEEDS=cassandra
        - CASSANDRA_PASSWORD_SEEDER=yes
        - CASSANDRA_PASSWORD=cassandra
      volumes:
        - ${MOUNT_BASE_PATH}/cassandra:/bitnami

