version: "3.9"
services:
    ######################################################
    ## Invoice Plane #####################################
    ######################################################
    invoiceplane:
        container_name: ${APP_PREFIX}invoiceplane
        image: mhzawadi/invoiceplane:dev
        volumes:
            - invoiceplane_data:/var/www/html/uploads
        environment:
            - TZ=utc
            - MYSQL_HOST=mariadb_10_4
            - MYSQL_USER=InvoicePlane
            - MYSQL_PASSWORD=invoiceplane
            - MYSQL_DB=InvoicePlane
            - IP_URL=${INVOICEPLANE_URL} ##http://invoiceplane.docker.local
            - DISABLE_SETUP=false
volumes:
    invoiceplane_data:
        driver: local
