version: "3.9"
services:
    ######################################################
    ## Keycloak ##########################################
    ## PORT: 8080 ########################################
    ######################################################
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:latest
        restart: unless-stopped
        volumes:
            - ${MOUNT_BASE_PATH}/keycloak:/opt/keycloak/data/import
        command: ["start-dev --import-realm"]
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=change_me
