version: "3.9"
services:
    ######################################################
    ## Kong ##############################################
    ######################################################
    codeserver:
        container_name: kong
        image: kong
        # ports:
        #   - 8000:8000
        #   - 8443:8443
        #   - 8001:8001
        #   - 8444:8444
        restart: unless-stopped
        # env_file: ${ENV_FILE_PATH}
        environment:
            - KONG_DATABASE=cassandra
            - KONG_CASSANDRA_CONTACT_POINTS=cassandra
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
            - KONG_PORTAL_GUI_HOST=localhost:8003
            - KONG_PORTAL=on kong reload exit
