version: "3.9"
services:
    ######################################################
    ## Loki ##############################################
    ######################################################
    loki:
        container_name: loki
        image: grafana/loki:2.6.1
        # ports:
        #   - "3100:3100"
        volumes:
            - ${MOUNT_BASE_PATH}/loki/config:/mnt/config
        command:
            - -config.file=/mnt/config/config.yaml