version: "3.9"
services:
    ############################################
    ### NGINX PROXY SERVICE ####################
    ############################################
    nginx:
        container_name: ${APP_PREFIX}nginx
        image: jc21/nginx-proxy-manager:latest
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - nginx_data:/data
            - letsencrypt:/etc/letsencrypt

volumes:
    nginx_data:
        driver: local
    letsencrypt:
        driver: local