version: "3.9"
services:
    ######################################################
    ## Portainer #########################################
    ## PORT: 9000 ########################################
    ######################################################
    portainer-ce:
        container_name: portainer-ce
        image: portainer/portainer-ce:latest
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - ${LOCAL_TIME_PATH}:/etc/localtime:ro
            - ${DOCKER_SOCK_PATH}:/var/run/docker.sock:ro
            - portainer_data:/data
        networks:
            - env-network

networks:
    env-network:
        name: ${NETWORK_NAME}
        external: true

volumes:
    portainer_data:
        driver: local
