version: "3.9"
services:
    ######################################################
    ## Portainer #########################################
    ## PORT: 9000 ########################################
    ######################################################
    portainer-ce:
        container_name: ${APP_PREFIX}portainer
        image: portainer/portainer-ce:latest
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - ${LOCAL_TIME_PATH}:/etc/localtime:ro
            - ${DOCKER_SOCK_PATH}:/var/run/docker.sock:ro
            - portainer_data:/data
            - ${MOUNT_BASE_PATH}:/mount
            - ${COMPOSE_BASE_PATH}:/compose
            - ${BUILD_BASE_PATH}:/build

volumes:
    portainer_data:
        driver: local
