version: "3.9"
services:
    ######################################################
    ## Rancher ###########################################
    ## PORT: 80 / 443 ####################################
    ######################################################
    rancher:
        container_name: rancher
        image: rancher/rancher
        privileged: true
        restart: unless-stopped
        networks:
            - env-network

networks:
    env-network:
        name: ${NETWORK_NAME}
        external: true
