version: "3.9"
services:
    ######################################################
    ## ZenTao ############################################
    ## PORT: 80 , 3306 ###################################
    ######################################################
    zentao:
        container_name: zentao
        image: idoop/zentao
        environment:
            - ADMINER_USER="root"
            - ADMINER_PASSWD="password"
            - BIND_ADDRESS="false"
        volumes:
            - ${MOUNT_BASE_PATH}/zentao:/opt/zbox/
        # extra_hosts:
        #     - smtp.email.qq.com:163.177.90.125
